insert into SexsualOrientation(SOName) values(N'Dị tính');
insert into SexsualOrientation(SOName) values(N'Đồng tính');
insert into SexsualOrientation(SOName) values(N'Đồng tính nữ');
insert into SexsualOrientation(SOName) values(N'Song tính');
insert into SexsualOrientation(SOName) values(N'Vô tính');
insert into SexsualOrientation(SOName) values(N'Á tính');
insert into SexsualOrientation(SOName) values(N'Toàn tính');
insert into SexsualOrientation(SOName) values(N'Queer');
insert into SexsualOrientation(SOName) values(N'Chưa xác định rõ khuynh hướng');

insert into Communication(CName) values(N'Nghiện nhắn tin');
INSERT INTO Communication(CName) VALUES (N'Yêu thư giãn');
INSERT INTO Communication(CName) VALUES (N'Chia sẻ hình ảnh');
INSERT INTO Communication(CName) VALUES (N'Cuộc gọi điện thoại');
INSERT INTO Communication(CName) VALUES (N'Tin nhắn ngắn');
INSERT INTO Communication(CName) VALUES (N'Video call');
INSERT INTO Communication(CName) VALUES (N'Gửi file đính kèm');
INSERT INTO Communication(CName) VALUES (N'Chat video trực tiếp');
INSERT INTO Communication(CName) VALUES (N'Tin nhắn thoại');
INSERT INTO Communication(CName) VALUES (N'Chat nhóm');

INSERT INTO LoveLanguage(LLName) VALUES (N'Những hành động tinh tế');
INSERT INTO LoveLanguage(LLName) VALUES (N'Tặng quà đáng yêu');
INSERT INTO LoveLanguage(LLName) VALUES (N'Chia sẻ thời gian chất lượng');
INSERT INTO LoveLanguage(LLName) VALUES (N'Tặng lời khen ngợi và khích lệ');
INSERT INTO LoveLanguage(LLName) VALUES (N'Chạm và kết nối vật lý');

INSERT INTO Pet(PName) VALUES (N'Chó');
INSERT INTO Pet(PName) VALUES (N'Mèo');
INSERT INTO Pet(PName) VALUES (N'Gà');
INSERT INTO Pet(PName) VALUES (N'Vịt');
INSERT INTO Pet(PName) VALUES (N'Hổ');
INSERT INTO Pet(PName) VALUES (N'Cá');
INSERT INTO Pet(PName) VALUES (N'Rùa');
INSERT INTO Pet(PName) VALUES (N'Ngựa');
INSERT INTO Pet(PName) VALUES (N'Lừa');
INSERT INTO Pet(PName) VALUES (N'Chuột');
INSERT INTO Pet(PName) VALUES (N'Rắn');
INSERT INTO Pet(PName) VALUES (N'Tắc kè');
INSERT INTO Pet(PName) VALUES (N'Khỉ');
INSERT INTO Pet(PName) VALUES (N'Gấu');
INSERT INTO Pet(PName) VALUES (N'Cừu');
INSERT INTO Pet(PName) VALUES (N'Cá heo');
INSERT INTO Pet(PName) VALUES (N'Mèo');
INSERT INTO Pet(PName) VALUES (N'Yêu thích nhưng không nuôi');
INSERT INTO Pet(PName) VALUES (N'Không nuôi thú cưng');
INSERT INTO Pet(PName) VALUES (N'Khác');
INSERT INTO Pet(PName) VALUES (N'Tất cả các loại thú cưng');
INSERT INTO Pet(PName) VALUES (N'Dị ứng với động vật');

INSERT INTO Alcolhol(AName) VALUES (N'Không dành cho mình');
INSERT INTO Alcolhol(AName) VALUES (N'Luôn tỉnh táo');
INSERT INTO Alcolhol(AName) VALUES (N'Uống có trách nhiệm');
INSERT INTO Alcolhol(AName) VALUES (N'Chỉ những dịp đặc biệt');
INSERT INTO Alcolhol(AName) VALUES (N'Uống những dịp cuối tuần');
INSERT INTO Alcolhol(AName) VALUES (N'Hầu như mỗi tối');

INSERT INTO Diet(DName) VALUES (N'Ăn thuần chay');
INSERT INTO Diet(DName) VALUES (N'Ăn chay');
INSERT INTO Diet(DName) VALUES (N'Chỉ ăn hải sản và rau củ');
INSERT INTO Diet(DName) VALUES (N'Kosher');
INSERT INTO Diet(DName) VALUES (N'Halal');
INSERT INTO Diet(DName) VALUES (N'Chỉ ăn thịt');
INSERT INTO Diet(DName) VALUES (N'Không ăn kiêng');
INSERT INTO Diet(DName) VALUES (N'Khác');

INSERT INTO VacxinCovid(VCName) VALUES (N'Đã được tiêm vacxin');
INSERT INTO VacxinCovid(VCName) VALUES (N'Chưa tiêm vacxin');
INSERT INTO VacxinCovid(VCName) VALUES (N'Không muốn nói');

INSERT INTO Zodiac(ZName) VALUES (N'Ma kết');
INSERT INTO Zodiac(ZName) VALUES (N'Bạch dương');
INSERT INTO Zodiac(ZName) VALUES (N'Kim ngưu');
INSERT INTO Zodiac(ZName) VALUES (N'Cự giải');
INSERT INTO Zodiac(ZName) VALUES (N'Sư tử');
INSERT INTO Zodiac(ZName) VALUES (N'Xử nữ');
INSERT INTO Zodiac(ZName) VALUES (N'Thiên bình');
INSERT INTO Zodiac(ZName) VALUES (N'Bọ cạp');
INSERT INTO Zodiac(ZName) VALUES (N'Nhân mã');
INSERT INTO Zodiac(ZName) VALUES (N'Thủy Bình');
INSERT INTO Zodiac(ZName) VALUES (N'Pisces');
INSERT INTO Zodiac(ZName) VALUES (N'Songs Ngư');


INSERT INTO Personality(PName) VALUES (N'INTJ');
INSERT INTO Personality(PName) VALUES (N'ENTJ');
INSERT INTO Personality(PName) VALUES (N'INTP');
INSERT INTO Personality(PName) VALUES (N'ENTP');
INSERT INTO Personality(PName) VALUES (N'INFJ');
INSERT INTO Personality(PName) VALUES (N'ENFJ');
INSERT INTO Personality(PName) VALUES (N'INFP');
INSERT INTO Personality(PName) VALUES (N'ENFP');
INSERT INTO Personality(PName) VALUES (N'ISTJ');
INSERT INTO Personality(PName) VALUES (N'ESTJ');
INSERT INTO Personality(PName) VALUES (N'ISFJ');
INSERT INTO Personality(PName) VALUES (N'ESFJ');
INSERT INTO Personality(PName) VALUES (N'ISTP');
INSERT INTO Personality(PName) VALUES (N'ESTP');
INSERT INTO Personality(PName) VALUES (N'ISFP');

INSERT INTO Smoke(SName) VALUES (N'Hút thuốc với bạn bè');
INSERT INTO Smoke(SName) VALUES (N'Hút thuốc một mình');
INSERT INTO Smoke(SName) VALUES (N'Không hút thuốc');
INSERT INTO Smoke(SName) VALUES (N'Hút thuốc xã giao');
INSERT INTO Smoke(SName) VALUES (N'Hút thuốc đôi khi');
INSERT INTO Smoke(SName) VALUES (N'Đang cố gắng bỏ');

INSERT INTO SocialMedia(SMName) VALUES (N'Influencer');
INSERT INTO SocialMedia(SMName) VALUES (N'Hoạt động tích cực');
INSERT INTO SocialMedia(SMName) VALUES (N'Không dùng mạng');
INSERT INTO SocialMedia(SMName) VALUES (N'Lướt dạo âm thầm');

INSERT INTO Education(EName) VALUES (N'Cử nhân');
INSERT INTO Education(EName) VALUES (N'Tiến sĩ');
INSERT INTO Education(EName) VALUES (N'Thạc sĩ');
INSERT INTO Education(EName) VALUES (N'Trung học phổ thông');
INSERT INTO Education(EName) VALUES (N'Không có bằng cấp');
INSERT INTO Education(EName) VALUES (N'Học nghề');
INSERT INTO Education(EName) VALUES (N'Đang học đại học');


INSERT INTO PurposeDate(PDName) VALUES (N'Người yêu');
INSERT INTO PurposeDate(PDName) VALUES (N'Bạn hẹn hò lâu dài');
INSERT INTO PurposeDate(PDName) VALUES (N'Bất kì điều gì có thể');
INSERT INTO PurposeDate(PDName) VALUES (N'Quan hệ không ràng buộc');
INSERT INTO PurposeDate(PDName) VALUES (N'Những người bạn mới');
INSERT INTO PurposeDate(PDName) VALUES (N'Mình cũng chưa rõ lắm');

INSERT INTO FutureFamily(FFName) VALUES (N'Mình muốn có con');
INSERT INTO FutureFamily(FFName) VALUES (N'Chưa quyết định');
INSERT INTO FutureFamily(FFName) VALUES (N'Mình không muốn có con');
INSERT INTO FutureFamily(FFName) VALUES (N'Con đã có sẵn');
INSERT INTO FutureFamily(FFName) VALUES (N'Không rõ');

INSERT INTO Workout(WName) VALUES (N'Hàng ngày');
INSERT INTO Workout(WName) VALUES (N'Thường xuyên');
INSERT INTO Workout(WName) VALUES (N'Thỉnh thoảng');
INSERT INTO Workout(WName) VALUES (N'Không tập');

INSERT INTO SleepHabit(SHName) VALUES (N'Dậy sớm');
INSERT INTO SleepHabit(SHName) VALUES (N'Cú đêm');
INSERT INTO SleepHabit(SHName) VALUES (N'Ngủ sớm dậy muộn');
INSERT INTO SleepHabit(SHName) VALUES (N'Không có thói quen cố định');

INSERT INTO Passion(PName) VALUES (N'Âm nhạc');
INSERT INTO Passion(PName) VALUES (N'Du lịch');
INSERT INTO Passion(PName) VALUES (N'Đọc sách');
INSERT INTO Passion(PName) VALUES (N'Thể thao');
INSERT INTO Passion(PName) VALUES (N'Nấu ăn');
INSERT INTO Passion(PName) VALUES (N'Chơi game');
INSERT INTO Passion(PName) VALUES (N'Xem phim');
INSERT INTO Passion(PName) VALUES (N'Chụp ảnh');
INSERT INTO Passion(PName) VALUES (N'Lập trình');
INSERT INTO Passion(PName) VALUES (N'Học ngoại ngữ');
INSERT INTO Passion(PName) VALUES (N'Thiết kế đồ họa');
INSERT INTO Passion(PName) VALUES (N'Trồng cây');
INSERT INTO Passion(PName) VALUES (N'Âm nhạc cổ điển');
INSERT INTO Passion(PName) VALUES (N'Điều hòa không khí');
INSERT INTO Passion(PName) VALUES (N'Tây du ký');
INSERT INTO Passion(PName) VALUES (N'Đá bóng');
INSERT INTO Passion(PName) VALUES (N'Đi bộ đường dài');
INSERT INTO Passion(PName) VALUES (N'Chơi guitar');
INSERT INTO Passion(PName) VALUES (N'Ngồi bên bờ biển');
INSERT INTO Passion(PName) VALUES (N'Học yoga');
INSERT INTO Passion(PName) VALUES (N'Xem bóng rổ');
INSERT INTO Passion(PName) VALUES (N'Gặp gỡ bạn bè');
INSERT INTO Passion(PName) VALUES (N'Dạo phố đêm');
INSERT INTO Passion(PName) VALUES (N'Chăm sóc động vật cưng');
INSERT INTO Passion(PName) VALUES (N'Vẽ tranh');
INSERT INTO Passion(PName) VALUES (N'Xem triển lãm nghệ thuật');
INSERT INTO Passion(PName) VALUES (N'Ngắm sao');
INSERT INTO Passion(PName) VALUES (N'Nghe podcast');
INSERT INTO Passion(PName) VALUES (N'Tập luyện thể dục');


INSERT INTO Languages(LName) VALUES (N'Tiếng Việt');
INSERT INTO Languages(LName) VALUES (N'Tiếng Anh');
INSERT INTO Languages(LName) VALUES (N'Tiếng Tây Ban Nha');
INSERT INTO Languages(LName) VALUES (N'Tiếng Pháp');
INSERT INTO Languages(LName) VALUES (N'Tiếng Đức');
INSERT INTO Languages(LName) VALUES (N'Tiếng Ý');
INSERT INTO Languages(Lname) VALUES (N'Tiếng Bồ Đào Nha');
INSERT INTO Languages(LName) VALUES (N'Tiếng Trung');
INSERT INTO Languages(LName) VALUES (N'Tiếng Nhật');
INSERT INTO Languages(LName) VALUES (N'Tiếng Hàn Quốc');
INSERT INTO Languages(LName) VALUES (N'Tiếng Nga');
INSERT INTO Languages(LName) VALUES (N'Tiếng Ả Rập');
INSERT INTO Languages(LName) VALUES (N'Tiếng Thổ Nhĩ Kỳ');
INSERT INTO Languages(LName) VALUES (N'Tiếng Hy Lạp');
INSERT INTO Languages(LName) VALUES (N'Tiếng Ba Lan');
INSERT INTO Languages(LName) VALUES (N'Tiếng Hà Lan');
INSERT INTO Languages(LName) VALUES (N'Tiếng Thụy Điển');
INSERT INTO Languages(LName) VALUES (N'Tiếng Đan Mạch');
INSERT INTO Languages(LName) VALUES (N'Tiếng Na Uy');
INSERT INTO Languages(LName) VALUES (N'Tiếng Phần Lan');
INSERT INTO Languages(LName) VALUES (N'Tiếng Hungari');
INSERT INTO Languages(LName) VALUES (N'Tiếng Séc');
INSERT INTO Languages(LName) VALUES (N'Tiếng Slovakia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Croatia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Serbia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Slovenia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Romania');
INSERT INTO Languages(LName) VALUES (N'Tiếng Bulgaria');
INSERT INTO Languages(LName) VALUES (N'Tiếng Macedonia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Bosnia và Hercegovina');
INSERT INTO Languages(LName) VALUES (N'Tiếng Kosovo');
INSERT INTO Languages(LName) VALUES (N'Tiếng Albania');
INSERT INTO Languages(LName) VALUES (N'Tiếng Montenegro');
INSERT INTO Languages(LName) VALUES (N'Tiếng Ukraine');
INSERT INTO Languages(LName) VALUES (N'Tiếng Belarus');
INSERT INTO Languages(LName) VALUES (N'Tiếng Moldova');
INSERT INTO Languages(LName) VALUES (N'Tiếng Georgia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Armenia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Azerbaijan');
INSERT INTO Languages(LName) VALUES (N'Tiếng Kazakhstan');
INSERT INTO Languages(LName) VALUES (N'Tiếng Uzbekistan');
INSERT INTO Languages(LName) VALUES (N'Tiếng Turkmenistan');
INSERT INTO Languages(LName) VALUES (N'Tiếng Kyrgyzstan');
INSERT INTO Languages(LName) VALUES (N'Tiếng Tajikistan');
INSERT INTO Languages(LName) VALUES (N'Tiếng Mongolia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Lào');
INSERT INTO Languages(LName) VALUES (N'Tiếng Campuchia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Thái Lan');
INSERT INTO Languages(LName) VALUES (N'Tiếng Malaysia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Indonesia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Singapore');
INSERT INTO Languages(LName) VALUES (N'Tiếng Philippines');
INSERT INTO Languages(LName) VALUES (N'Tiếng Myanmar');
INSERT INTO Languages(LName) VALUES (N'Tiếng Brunei');
INSERT INTO Languages(LName) VALUES (N'Tiếng East Timor');
INSERT INTO Languages(LName) VALUES (N'Tiếng Việt Nam');
INSERT INTO Languages(LName) VALUES (N'Tiếng Thổ Nhĩ Kỳ');
INSERT INTO Languages(LName) VALUES (N'Tiếng Hy Lạp');
INSERT INTO Languages(LName) VALUES (N'Tiếng Ba Lan');
INSERT INTO Languages(LName) VALUES (N'Tiếng Hà Lan');
INSERT INTO Languages(LName) VALUES (N'Tiếng Thụy Điển');
INSERT INTO Languages(LName) VALUES (N'Tiếng Đan Mạch');
INSERT INTO Languages(LName) VALUES (N'Tiếng Na Uy');
INSERT INTO Languages(LName) VALUES (N'Tiếng Phần Lan');
INSERT INTO Languages(LName) VALUES (N'Tiếng Hungari');
INSERT INTO Languages(LName) VALUES (N'Tiếng Séc');
INSERT INTO Languages(LName) VALUES (N'Tiếng Slovakia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Croatia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Serbia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Slovenia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Romania');
INSERT INTO Languages(LName) VALUES (N'Tiếng Bulgaria');
INSERT INTO Languages(LName) VALUES (N'Tiếng Macedonia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Bosnia và Hercegovina');
INSERT INTO Languages(LName) VALUES (N'Tiếng Kosovo');
INSERT INTO Languages(LName) VALUES (N'Tiếng Albania');
INSERT INTO Languages(LName) VALUES (N'Tiếng Montenegro');
INSERT INTO Languages(LName) VALUES (N'Tiếng Ukraine');
INSERT INTO Languages(LName) VALUES (N'Tiếng Belarus');
INSERT INTO Languages(LName) VALUES (N'Tiếng Moldova');
INSERT INTO Languages(LName) VALUES (N'Tiếng Georgia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Armenia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Azerbaijan');
INSERT INTO Languages(LName) VALUES (N'Tiếng Kazakhstan');
INSERT INTO Languages(LName) VALUES (N'Tiếng Uzbekistan');
INSERT INTO Languages(LName) VALUES (N'Tiếng Turkmenistan');
INSERT INTO Languages(LName) VALUES (N'Tiếng Kyrgyzstan');
INSERT INTO Languages(LName) VALUES (N'Tiếng Tajikistan');
INSERT INTO Languages(LName) VALUES (N'Tiếng Mongolia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Lào');
INSERT INTO Languages(LName) VALUES (N'Tiếng Campuchia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Thái Lan');
INSERT INTO Languages(LName) VALUES (N'Tiếng Malaysia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Indonesia');
INSERT INTO Languages(LName) VALUES (N'Tiếng Singapore');
INSERT INTO Languages(LName) VALUES (N'Tiếng Philippines');
INSERT INTO Languages(LName) VALUES (N'Tiếng Myanmar');
INSERT INTO Languages(LName) VALUES (N'Tiếng Brunei');
INSERT INTO Languages(LName) VALUES (N'Tiếng East Timor');






